//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_From.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int Id { get; set; }
        [DisplayName("First Name")]
        [Required(ErrorMessage ="First name is a required field")]
        public string firstName { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Last name is a required field")]
        public string lastName { get; set; }
        [DisplayName("Gender")]
        [Required(ErrorMessage = "Gender is a required field")]
        public string gender { get; set; }
        [DisplayName("Age")]
        [Required(ErrorMessage = "Age is a required field")]
        public int age { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Email is a required field")]
        public string email { get; set; }
        [DisplayName("Username")]
        [Required(ErrorMessage = "Username is a required field")]
        public string username { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is a required field")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [DisplayName("confirm Password")]
        [Required(ErrorMessage = "Confirm Password is a required field")]
        [DataType(DataType.Password)]
        [Compare("password", ErrorMessage ="Password is not identical")]
        public string confirm_password { get; set; }
    }
}
